### ISSUE TITLE
Showcase Components

### ISSUE THREAD

**Issue by Djspaceg** [enactjs/agate#11]
We'll need a way to demonstrate our new components one at a time and show off their features. We've done this for other themes using Storybook (enact/sampler). Having a Sampler for agate components will really help with not only showing features, usage, and options; but also help later on with testing.

* Create an Agate section for Storybook that we can populate with stories for each new component added to the theme.
* Create an AgateEnvironment (like MoonstoneEnvironment) component as a wrapper for these stories that will act as a root decorator for each story.

**Comment by teckliew** [comment]
Initialized Storybook in `agate-apps`:
https://github.com/enactjs/agate-apps/commit/0bed599c8628424836cc164a5c711c54f35699fb

So far there's just a button sample, feel free to add more. Probably a good idea to communicate here if you are adding new component story to the Storybook sampler.

**Comment by Djspaceg** [comment]
Initial work is done. Let's close this out. I'll move the "Project" to the other repo to better reflect where the actual work is being done.
