### ISSUE TITLE
Create Divider

### ISSUE THREAD

**Issue by Djspaceg** [enactjs/agate#13]
SUPER Simple. Every good UI needs to have a divider with a title on it, like the following images:

<img width="524" alt="screen shot 2018-08-29 at 2 52 06 pm" src="https://user-images.githubusercontent.com/386529/44817766-47f02080-ab9b-11e8-8fd7-d78bc553a942.png">
<img width="196" alt="screen shot 2018-08-29 at 2 52 33 pm" src="https://user-images.githubusercontent.com/386529/44817769-4b83a780-ab9b-11e8-9d1b-15414da60f90.png">

**Comment by rundmt** [comment]
Merged
