### ISSUE TITLE
Build Popup

### ISSUE THREAD

**Issue by Djspaceg** [enactjs/agate#15]
Conveying momentary information is important to any UI. We need a popup that supports an arbitrary amount of content and flexes in both height and width depending on the size of the content and remains centered on the viewing area.

General thoughts:
We can probably assume that we'll want each popup to include a close button `Button with Icon` and a title `Divider`.

**Comment by sugardave** [comment]
Have an `agate/Popup`: https://github.com/enactjs/agate/pull/24
