### ISSUE TITLE
Create Agate Template Starting Point

### ISSUE THREAD

**Issue by Djspaceg** [enactjs/agate#23]
## Description

We'll need a starting point for new users to be able to work from.

This starting point app template should have several components already built and displaying so new users get something more useful out of the box than just a "hello world".

## Requirements

Built-in pieces to have:
1. An `agate/Panels` implementation with 2 panels and 2 tabs to switch between them
   * Only one of the panels needs some content, but a button or something on the second one wouldn't hurt.
   * Having some pre-built state management to support Panel switching, written in an idealized way, would be great for getting users started right out of the box
2. Include comments directly in the code for `App.js` or `index.js` that lists what "skins" are available: "carbon" and "titanium", that "carbon" is default, and how to use them.
`<App skin="titanium">`
Explain that carbon is a dark theme and the titanium is light, so they don't have to try them both out before they can decide.
3. Include some interesting looking components on one of the Panels: `Button`, `Input`, `Picker`, `SliderButton`, or `Popup`.
   * May be good to wire up one of the components to have some visible action to illustrate fundamentals of how events are passed around.

## To Deliver
Either a distributable ZIP file, a standalone repo, or built-in app templates for Enact CLI will work. We just need at least one of them.

**Comment by JayCanuck** [comment]
Probably ideal to put it on https://github.com/enactjs/templates and publish to npm similar to the style as the others.

**Comment by webOS101** [comment]
Be sure to pull in the zoom prevention code from the console app.

**Comment by ryanjduffy** [comment]
We decided to publish the template in alpha form from a working branch (`feature/agate`) and then merge enactjs/templates#4 once we are satisfied it's ready.

https://www.npmjs.com/package/@enact/template-agate
