### ISSUE TITLE
Create ToggleButton

### ISSUE THREAD

**Issue by teckliew** [enactjs/agate#25]
<img width="331" alt="screen shot 2018-09-05 at 9 48 22 am" src="https://user-images.githubusercontent.com/8940009/45108245-f0990580-b0f0-11e8-83f1-9a2935af76cb.png">
<img width="189" alt="screen shot 2018-09-05 at 9 48 56 am" src="https://user-images.githubusercontent.com/8940009/45108244-f0990580-b0f0-11e8-8c54-5f63b958be30.png">

**Comment by teckliew** [comment]
pr: https://github.com/enactjs/agate/pull/35
sample: https://github.com/enactjs/agate-apps/pull/16

**Comment by ryanjduffy** [comment]
@teckliew Thanks for pulling this together. It's a great start! Couple notes from integrating this into the HVAC screen:

* I think the `toggleIndicator` prop is misplaced here. I _think_ the two "indicators" display on the HVAC screen are referring to levels (low/high) so I don't think we need such a prop on `agate/ToggleButton` but instead some type of custom implementation for HVAC.
* I noticed that it's difficult/impossible to tell when a selected ToggleButton is focused in `titanium`. Looks fine in `carbon`.

**Comment by teckliew** [comment]
I'll get back to this and remove the `toggleIndicator` prop and replace it with an underline prop.
