### ISSUE TITLE
IconItem: handle long content

### ISSUE THREAD

**Issue by teckliew** [enactjs/agate#28]
## Description
`IconItem` doesn't handle long content properly. (refer to how `Item` handles it with `Marquee`).

✅
<img width="706" alt="item" src="https://user-images.githubusercontent.com/8940009/45128847-1fd16600-b135-11e8-98cd-1ea475147526.png">
✅
<img width="709" alt="item-focus" src="https://user-images.githubusercontent.com/8940009/45128846-1fd16600-b135-11e8-8aef-d9958d748ab3.png">
❌
<img width="724" alt="iconitem" src="https://user-images.githubusercontent.com/8940009/45128848-1fd16600-b135-11e8-860e-3ed6b19e4f32.png">
❌
<img width="715" alt="iconitem-focus" src="https://user-images.githubusercontent.com/8940009/45128845-1fd16600-b135-11e8-8f90-520ce8ad2175.png">

**Comment by ryanjduffy** [comment]
Not sure if we want to adopt Marquee outside of the TV. It might be better to support wrapped text instead. I'd be concerned that marqueeing text would be distracting in the automotive space.

**Comment by sugardave** [comment]
Punting until there is some UX discussion about overall marquee usage in auto applications.
