### ISSUE TITLE
SwitchItem won't toggle off

### ISSUE THREAD

**Issue by sugardave** [enactjs/agate#30]
If you have `<SwitchItem selected>...` it will remain "on" forever.

**Comment by webOS101** [comment]
Isn't that expected behavior?  did you mean `defaultSelected`?

**Comment by teckliew** [comment]
I don't think `SwitchItem` takes in `defaultSelected`, maybe wrap it in `Toggleable`?

**Comment by rundmt** [comment]
We are already using `Toggleable`, and we do have `defaultSelected` available so I think I'm going to close this out. If there are any objections feel free to open this back up. I'll add a knob in storybook to be more obvious about the prop though.
