### ISSUE TITLE
Input Component should include icon?

### ISSUE THREAD

**Issue by hangyeolryu** [enactjs/agate#46]
### Current situation
The `<Input>` on the phone tab in the console app uses an `<Icon>` component to delete one string by one from the right (acting like backspace). This `<Icon>` is used outside of `<Input>`. With this, the consumers who use this component will have to implement all the logic, functionality and styling outside the `<Input>` component. 
- Delete from the right
- Delete from the middle of the input string when the cursor position changes
- Focus back to the input after deleting
- border-bottom should be extended to go under the icon, and padding-right should be added for icon in input.

### Suggestion
Since the functionalities and styles are directly/only for `Input`, I think the `Icon` should be included in the `Input`. To support this, we we check the native html inputs in different browsers, we get the x delete button for the input and it's inside the input box.

![image](https://user-images.githubusercontent.com/8715394/45394718-e2625200-b5e6-11e8-9d9e-d8dadcd20c30.png)

If we want to have a different type of input like `SearchInput`, we can create a new component for it. Or, we can have a prop to set the type of input or an icon prop and provide according functionalities. In this way, we are able to have consistent UX and design for different types of inputs across the board.

**Comment by webOS101** [comment]
It's perhaps worth noting that in the case where we need to lock spotlight (as in Moonstone `Input`) that the exterior delete button would not be usable without clicking twice (once to dismiss the keyboard/scrim) and the 2nd to activate the button.  That would be a very poor UX.

**Comment by haileyR** [comment]
Yes, with the current input, we have to click the delete btn twice to start deleting.

**Comment by rundmt** [comment]
I think adding icon to input as a prop makes sense. Especially if the inline styling is going to be the same whether it's a search or a delete button. We can just add some hooks to the button and compose new components based on it.

**Comment by Djspaceg** [comment]
I'd like to see this be implemented as a ComponentOverride in an icon slot. We attach some default attributes to the built-in component, but then allow users to provide their own icon and attach whatever event handers or attributes they want to it. The end result would be something like this:
```
<Input onChange={myOnChangeCallback} defaultValue={this.state.myInputValue}>
   <icon>
      <Icon className={css.myInputIcon} onTap={myIconCallbackFunction} />
   </icon>
</Input>
```
or with fewer lines:
```
<Input onChange={myOnChangeCallback} defaultValue={this.state.myInputValue}>
   <Icon slot="icon" className={css.myInputIcon} onTap={myIconCallbackFunction} />
</Input>
```

**Comment by ryanjduffy** [comment]
... just testing ...

**Comment by haileyR** [comment]
@djspaceg I like the idea. That way, we can control on the styling much easier, right?

**Comment by Djspaceg** [comment]
@haileyR Yep! Styling, event assignment, all of it.

**Comment by haileyR** [comment]
@djspaceg 
Hm, for delete actions (with the backspace icon), should consumers still need to implement the event handlers? If so, it will be too much work for them. It will including not only deleting from the end of the string but it should track the cursor position where it should delete from. How do you think about this usecase?

**Comment by webOS101** [comment]
We should also decide if such components can be spottable (as focusing via 5-way would blur the input, invalidating the current location).

**Comment by haileyR** [comment]
Yea. If we decide that this agate is only for cars. We have fixed number of different types of inputs and maybe behaviors, too. 
So it would be much easier to just start building what we exactly need. This component library doesn’t have to support all different kinds of cases.

**Comment by webOS101** [comment]
We can implement the specialized input in the phone app as opposed to the library, given it has a single purpose (right now?)

**Comment by Djspaceg** [comment]
In fact, a phone number input may even be too specialized for a framework component and should possibly live exclusively in the console app's Phone code (in the app's `components/` folder). This way, `agate/Input` can remain generic and universal. What do you think?

**Comment by haileyR** [comment]
I mean “what is agate for”. What do we want to support with this.

**Comment by Djspaceg** [comment]
If during the construction of the specialized phone number input you discover that it could easily be made reusable and customizable, we could certainly bring it into agate as a first-class component. I've got no problem with that.

**Comment by haileyR** [comment]
It will still depend on what we want to support. From my point of view, agate is for car apps for different consumers. They will all have those different kinds of inputs for phone oriented. Since that was my understanding of agate and a "phone component" library, I was suggesting building those ready-to-use components. However, if my understanding is not what we want as a team, I can build this phone number input component in console app. LMK! :)

**Comment by Djspaceg** [comment]
@haileyR, Please build the phone number input component as a Console app component initially. While you're constructing it, consider how it could be customized by a framework consumer and what some good defaults would be if it were to be included in the Agate theme. If at the end of this research/construction project, you feel it should become a first-tier unique and customizable framework component, let's move it into Agate at that time. Moving a well-structured component from Console app to Agate should be very easy (just a few minutes). I'm excited to see what you come up with!

_Thoughts/Reasoning:_
From my current understanding, and I'm certainly not the authority on this matter, a typical automotive UI would have only one place/usage for a phone number input (in the phone app), and the UI/UX for it would be very brand-specific. A phone number input component will need lots of ways to be customizable to suit a wide variety of consumers needs. This wide assortment of implementation options is why I suggest building it as an app component first; we can get a feel for how complicated the API is, what it needs to support, and how customizable it should be, before committing to including such an opinionated component into the Agate theme.

**Comment by Djspaceg** [comment]
How's the progress on this `input` component going, @haileyR?
