### ISSUE TITLE
Picker: need to come up with a better way to do state received from props.

### ISSUE THREAD

**Issue by rundmt** [enactjs/agate#49]
When trying to use Picker with outside services it didn't update easily. Now we adjusted it to be able to getDerivedStateFromProps. This allows us to still use the Picker logic and allow outside apps to handle it easily. This works fine so far, but there could be some better ways to implement this logic. 

We may want to come up with a breakdown between PickerBase and Picker that we see in Moonstone. Maybe what we have now is a good middle ground, but I'm sure other components with trickier states may run into similar problems so we should come up with a more standard solution.

**Comment by ryanjduffy** [comment]
The standard approach within Enact for managing controlled vs uncontrolled component is to either:
* Accept a `defaultXXX` prop to set an initial value and allow the component to control the value from that point on
* Accept the `XXX` prop and allow the consumer to control the value based on external events or the event callbacks supported by the component.

For the common use cases, this capability is codified into `Changeable` and `Toggleable` but has also been built into a few other components.

I've refactored Picker a bit to use `Changeable` and will submit a PR where we can discuss further.
