### ISSUE TITLE
Develop Third Theme (New Visuals)

### ISSUE THREAD

**Issue by Djspaceg** [enactjs/agate#58]
We can illustrate how easily we can retheme our automotive framework by having several unique looking visual styles.

* Give it a name
* Create a new visual style using the `agate/styles/colors.less` and `agate/styles/variables.less` files
* Add it to the `skins.less` `applySkins()` mixin
* Add it to the `agate/Skinnable.js` file
* Add it to the skin switcher in Agate Storybook

**Comment by teckliew** [comment]
https://github.com/enactjs/agate/pull/65
https://github.com/enactjs/agate-apps/pull/63
